services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Run at 4 AM daily
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Watchtower (Pi)
      - homepage.icon=watchtower.png
      - homepage.href=http://192.168.50.216:8081/v1/metrics
      - homepage.description=Service updater
      - homepage.siteMonitor=http://192.168.50.216:8081/v1/metrics
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://192.168.50.216:8081
      - homepage.widget.key=${WATCHTOWER_HTTP_API_TOKEN}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
