services:
  # Kavita is a fast, feature rich, cross platform reading server
  # https://github.com/Kareadita/Kavita
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    volumes:
      - ./config:/config
      - ../../Media/books:/books
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Kavita
      - homepage.icon=kavita.png
      - homepage.href=https://kavita.benlawson.dev/
      - homepage.siteMonitor=http://kavita:5000
      - homepage.description=Ebook & comic server
      - homepage.widget.type=kavita
      - homepage.widget.url=http://kavita:5000
      - homepage.widget.key=${KAVITA_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
