services:
  palworld:
    image: jammsen/palworld-dedicated-server:latest@sha256:ee924ca970450f59c89656953367c42c07327a7cdffc66f156be285dccae93c8
    container_name: palworld
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/palworld
    ports:
      - 8211:8211
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    labels:
      - homepage.group=Gaming
      - homepage.name=Palworld
      - homepage.icon=/icons/palworld.png
      - homepage.description=Palworld Dedicated Server
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=palworld
      - homepage.widget.url=udp://palworld:8211
      - homepage.widget.fields=["status", "currentPlayers", "maxPlayers"]
