version: "3"
services: 
  palworld: 
    image: jammsen/palworld-dedicated-server:latest
    container_name: palworld
    restart: unless-stopped
    network_mode: bridge
    volumes: 
      - E:\Docker\palworld\data:/palworld
    ports: 
      - 8211:8211
    env_file:
      - .env
