# NVIDIA SMI REST API - Exposes GPU stats for Homepage
# https://github.com/Opa-/nvidia-smi-rest
services:
  nvidia-smi-rest:
    image: opaopa/nvidia-smi-rest:latest@sha256:451d4a3f201837cd0e60e5c284d48934fe6fcc0d06c371682411e2f33958e3bb
    container_name: nvidia-smi-rest
    ports:
      - 7777:7777
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
    restart: unless-stopped
    labels:
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Observability
      - swag.uptime-kuma.monitor.url=http://nvidia-smi-rest:7777
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
    external: true
