services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OLLAMA_BASE_URL=http://lazytainer:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_NAME=${WEBUI_NAME}
    env_file:
      - .env
    volumes:
      - ./data:/app/backend/data
    restart: unless-stopped
    networks:
      - proxynet
    labels:
      - lazytainer.group=ai
      - homepage.group=Infrastructure
      - homepage.name=Open WebUI
      - homepage.icon=/icons/openwebui.png
      - homepage.href=https://ai.benlawson.dev/
      - homepage.description=AI Chat Interface

networks:
  proxynet:
    external:
      name: proxynet

