services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.1@sha256:6bb1fbe8ab0a3e0456067f493044ffb66a30a65a34be47f6a5862176a370dd16
    container_name: open-webui
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_NAME=${WEBUI_NAME}
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    volumes:
      - ./data:/app/backend/data
    ports:
      - 3333:8080
    restart: unless-stopped
    networks:
      - proxynet
    labels:
      - homepage.group=AI & Automation
      - homepage.name=Open WebUI
      - homepage.icon=/icons/openwebui.png
      - homepage.href=https://ai.benlawson.dev/
      - homepage.description=AI Chat Interface
      - swag_ondemand=enable
      - swag_ondemand_urls=https://ai.
      - 'swag_server_custom_directive=include /config/nginx/ondemand.conf;'
      - swag.uptime-kuma.enabled=false
      - swag.uptime-kuma.monitor.parent=AI & Automation
      - swag.uptime-kuma.monitor.url=https://ai.benlawson.dev/

networks:
  proxynet:
    external: true
    name: proxynet
