services:
  # Sonarr is used to query, add downloads to the download queue and index TV shows
  # https://sonarr.tv/
  sonarr:
    image: lscr.io/linuxserver/sonarr:version-4.0.19.2979@sha256:24acea2956a0ccb11f103877d9f4f8576600fb34bff34820ed749c2256dab89f
    container_name: sonarr
    volumes:
      - ../../Media:/data
      - ./config:/config
    ports:
      - 8989:8989
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - homepage.group=Media Management
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=https://sonarr.benlawson.dev/
      - homepage.siteMonitor=http://sonarr:8989/ping
      - homepage.description=Series management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Management
      - swag.uptime-kuma.monitor.url=https://sonarr.benlawson.dev/ping
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
