services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:version-v2.18.1@sha256:13f03ecfc61a7af89d492677389771ac29682a72153ce08a5cd4faffbc0197e8
    container_name: tautulli
    volumes:
      - ./config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    labels:
      - homepage.group=Observability
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=https://tautulli.benlawson.dev/
      - homepage.siteMonitor=http://tautulli:8181/status
      - homepage.description=Plex metrics
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181
      - homepage.widget.key=${TAUTULLI_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Observability
      - swag.uptime-kuma.monitor.url=https://tautulli.benlawson.dev/status
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
