# Glances - Cross-platform system monitoring tool
# https://github.com/nicolargo/glances
services:
  glances:
    container_name: glances-pi
    image: nicolargo/glances:latest-full@sha256:60872a1af0e40a3150975617c7e811ad7ad48f95bc45d033fb0c1737a037e4d2
    ports:
      - "61208:61208"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    labels:
      - homepage.group=Observability
      - homepage.name=Pi System Monitor
      - homepage.icon=glances.png
      - homepage.href=https://glances.benlawson.dev
      - homepage.description=Pi 3 system stats
      - homepage.siteMonitor=http://192.168.50.216:61208
      - homepage.widget.type=glances
      - homepage.widget.url=http://192.168.50.216:61208
      - homepage.widget.version=4
      - homepage.widget.metric=info
    pid: host
    restart: unless-stopped
