services:
  server:
    restart: unless-stopped
    container_name: ark
    image: hermsi/ark-server:latest-1784616424
    volumes:
      - ${HOME}/ark-server:/app
      - ${HOME}/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME="A Tranquil Environment"
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_STOP=${BACKUP_ON_STOP}
      - PRE_UPDATE_BACKUP=${PRE_UPDATE_BACKUP}
      - WARN_ON_STOP=${WARN_ON_STOP}
      - ENABLE_CROSSPLAY=true
      - DISABLE_BATTLEYE=true
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    ports:
      # Port for connections from ARK game client
      - "7779:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7780:7778/udp"
      # RCON management port
      - "27021:27020/tcp"
      # Steam's server-list port
      - "27016:27015/udp"
    networks:
      - default
      - proxynet
    labels:
      - homepage.group=Gaming
      - homepage.name=ARK Survival Evolved
      - homepage.icon=/icons/ark-survival-evolved.png
      - homepage.description=ARK SE Server
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=ase
      - homepage.widget.url=udp://ark:27015
      - homepage.widget.fields=["status", "currentPlayers", "maxPlayers", "map"]
    deploy:
      resources:
        limits:
          memory: 8G

networks:
  proxynet:
    external: true
    name: proxynet