services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - homepage.group=Media
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://overseerr.benlawson.dev/
      - homepage.siteMonitor=http://overseerr:5055
      - homepage.description=Media requests
      - homepage.widget.type=overseerr
      - homepage.widget.url=http://overseerr:5055
      - homepage.widget.key=${OVERSEERR_API_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet