apiVersion: 1

policies:
  - orgId: 1
    receiver: Discord - Lawson
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Autobrr IRC Recovery
        object_matchers:
          - [automation, =, autobrr-irc-recovery]
        group_by:
          - alertname
          - network
        group_wait: 0s
        group_interval: 5m
        repeat_interval: 30m
