apiVersion: 1

templates:
  - orgId: 1
    name: discord_template
    template: |
      {{ define "discord.title" }}
        {{ if eq .Status "firing" }}🔥 [FIRING:{{ .Alerts.Firing | len }}] {{ else }}✅ [RESOLVED] {{ end }}{{ .GroupLabels.alertname }}
      {{ end }}

      {{ define "discord.message" }}
        {{ range .Alerts }}
          **Alert:** {{ .Labels.alertname }}
          **Severity:** {{ .Labels.severity }}
          {{ if .Annotations.summary }}**Summary:** {{ .Annotations.summary }}{{ end }}
          {{ if .Annotations.description }}**Description:** {{ .Annotations.description }}{{ end }}
          {{ if .DashboardURL }}**Dashboard:** [View Dashboard]({{ .DashboardURL }}){{ end }}
          {{ if .PanelURL }}**Panel:** [View Panel]({{ .PanelURL }}){{ end }}
          ---
        {{ end }}
      {{ end }}
