services:
  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    container_name: actual-ai
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet