services:
  actual-ai:
    image: docker.io/sakowicz/actual-ai:latest
    container_name: actual-ai
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet