services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    image: ghcr.io/bitwarden/lite:latest@sha256:01181904fd02020dbc4d0598dd31a153b3784abd8a4d3ac9099fc1a939a58e6e
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - "8083:8080"
      - "8084:8443"
    volumes:
      - ./config:/etc/bitwarden
      - ./logs:/var/log/bitwarden
    networks:
      - proxynet
    deploy:
      resources:
        limits:
          memory: 2G
    labels:
      - "homepage.group=Infrastructure"
      - "homepage.name=Bitwarden"
      - "homepage.icon=bitwarden.png"
      - "homepage.href=https://bitwarden.benlawson.dev"
      - "homepage.description=Password Manager"
      - "homepage.siteMonitor=http://bitwarden:8080/alive"
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Infrastructure
      - swag.uptime-kuma.monitor.url=https://bitwarden.benlawson.dev/

  db:
    env_file:
      - path: db.env
      - path: db.env.secret
        required: false
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet

volumes:
  bitwarden:
  logs:
  data:
