services:
  # Prowlarr is our torrent indexer/searcher. Sonarr/Radarr use Prowlarr as a source
  # https://prowlarr.com/
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.4.0.5397-ls149
    container_name: prowlarr
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    labels:
      - homepage.group=Media Management
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.benlawson.dev/
      - homepage.siteMonitor=http://prowlarr:9696/ping
      - homepage.description=Index manager
      - homepage.widget.type=prowlarr
      - homepage.widget.fields=["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Management
      - swag.uptime-kuma.monitor.url=https://prowlarr.benlawson.dev/ping
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
