services:
  # Prowlarr is our torrent indexer/searcher. Sonarr/Radarr use Prowlarr as a source
  # https://prowlarr.com/
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - homepage.group=Management
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.benlawson.dev/
      - homepage.siteMonitor=http://prowlarr:9696/ping
      - homepage.description=Index manager
      - homepage.widget.type=prowlarr
      - homepage.widget.fields=["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
