services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.36.0
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - ../../Media/audiobooks:/audiobooks
      - ../../Media/books:/books
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=America/New_York
    labels:
      - homepage.group=Media Consumption
      - homepage.name=Audiobookshelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=https://audiobookshelf.benlawson.dev/
      - homepage.siteMonitor=http://audiobookshelf:80
      - homepage.description=Audiobook & podcast server
      - homepage.widget.type=audiobookshelf
      - homepage.widget.url=http://audiobookshelf:80
      - homepage.widget.key=${AUDIOBOOKSHELF_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Consumption
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
