services:
  unpackerr:
    image: golift/unpackerr:latest@sha256:244fc45cb207308f60e8f52dd703c2b3463385752de0f9517c58ff9d331ed15e
    container_name: unpackerr
    volumes:
      - ./data:/config
      - ../../Media:/data
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      ## Sonarr Settings
      - UN_SONARR_0_URL=${UN_SONARR_0_URL}
      - UN_SONARR_0_API_KEY=${UN_SONARR_0_API_KEY}
      - UN_SONARR_0_PATHS_0=${UN_SONARR_0_PATHS_0}
      ## Radarr Settings
      - UN_RADARR_0_URL=${UN_RADARR_0_URL}
      - UN_RADARR_0_API_KEY=${UN_RADARR_0_API_KEY}
      - UN_RADARR_0_PATHS_0=${UN_RADARR_0_PATHS_0}
      ## Readarr Settings
      - UN_READARR_0_URL=${UN_READARR_0_URL}
      - UN_READARR_0_API_KEY=${UN_READARR_0_API_KEY}
      - UN_READARR_0_PATHS_0=${UN_READARR_0_PATHS_0}
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet