services:
  lazywarden:
    container_name: lazywarden
    hostname: lazywarden
    image: querylab/lazywarden:latest@sha256:ed1829a473cd7ce0e164bdef3f2fffebbd66da3389e467875855bb5313e4002f
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    environment:
      UNLOCK_VAULT: "true"
    volumes:
      - ./config:/root/lazywarden/config
      - ./data:/root/lazywarden/backup-drive/
      - ./.env.secret:/app/.env:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - proxynet
    labels:
      - "homepage.group=Infrastructure"
      - "homepage.name=LazyWarden"
      - "homepage.icon=bitwarden.png"
      - "homepage.href=http://lazywarden:8080"
      - "homepage.description=Bitwarden backup and management tool"
      - "homepage.weight=5"

networks:
  proxynet:
    name: proxynet
