services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - ./config:/etc/prometheus
      - ./data:/prometheus
    labels:
      - homepage.group=Observability
      - homepage.name=Prometheus
      - homepage.icon=prometheus.png
      - homepage.href=https://prometheus.benlawson.dev/
      - homepage.siteMonitor=http://prometheus:9090/-/healthy
      - homepage.description=Metrics database
      - homepage.widget.type=prometheus
      - homepage.widget.url=http://prometheus:9090
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Observability
      - swag.uptime-kuma.monitor.url=https://prometheus.benlawson.dev/-/healthy
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet