services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/etc/dashboards:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - .env
    labels:
      - homepage.group=Observability
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=https://grafana.benlawson.dev/
      - homepage.siteMonitor=http://grafana:3000/healthz
      - homepage.description=Metric visualizations
      - homepage.widget.type=grafana
      - homepage.widget.url=http://grafana:3000
      - homepage.widget.username=rubiss
      - homepage.widget.password=${GRAFANA_PASSWORD}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Observability
      - swag.uptime-kuma.monitor.url=https://grafana.benlawson.dev/healthz
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet