services:
  epg:
    image: python:3.11-slim
    container_name: epg
    ports:
      - "3333:8000"  # Access guide at http://epg:8000/guide.xml for Plex
    volumes:
      - ./channels.xml:/app/channels.xml
      - ./epg_grabber.py:/app/epg_grabber.py
      - ./epg_server.py:/app/epg_server.py
    working_dir: /app
    environment:
      - TZ=America/New_York
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install --no-cache-dir requests beautifulsoup4 lxml flask schedule && 
             python epg_server.py"
    restart: unless-stopped
    networks:
        - proxynet

networks:
  proxynet:
    external:
        name: proxynet