services:
  # Radarr is used to query, add downloads to the download queue and index Movies
  # https://radarr.video/
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ../../Media:/data
      - ./config:/config
    ports:
      - 7878:7878
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - .env
    labels:
      - homepage.group=Media Management
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.benlawson.dev/
      - homepage.siteMonitor=http://radarr:7878/ping
      - homepage.description=Movie management
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Management
      - swag.uptime-kuma.monitor.url=https://radarr.benlawson.dev/ping
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
