services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 11 * * *  # Run at 6 AM EST (11 AM UTC) - 1 hour after Docker restart at 5 AM
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Watchtower
      - homepage.icon=watchtower.png
      - homepage.href=https://watchtower.benlawson.dev/v1/metrics
      - homepage.siteMonitor=http://watchtower:8080/v1/metrics
      - homepage.description=Service updater
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://watchtower:8080
      - homepage.widget.key=${HOMEPAGE_WIDGET_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
