services:
  cloudflare-duc:
    image: morl0ck/cloudflare-duc-go
    container_name: cloudflare-duc
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_NAME=benlawson.dev
      - CF_RECORD_NAME=public.benlawson.dev
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-5}
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet