services:
  cloudflare-duc:
    image: morl0ck/cloudflare-duc-go:latest@sha256:a0a2b0b2f80509c295195f7c59ce9f01d12ed851aae833c255ab5b009656c7cc
    container_name: cloudflare-duc
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_NAME=benlawson.dev
      - CF_RECORD_NAME=public.benlawson.dev
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-5}
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    restart: unless-stopped
