version: '2.4'

services:
  ark-ascended:
    image: sknnr/ark-ascended-server:latest
    container_name: ark-survival-ascended-server
    ports:
      - "7777:7777/udp"
      - "27020:27020/tcp"
    environment:
      - SESSION_NAME=ATranquilEnvironment
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - SERVER_MAP=TheIsland_WP
      - SERVER_ADMIN_PASSWORD=${SERVER_ADMIN_PASSWORD}
      - GAME_PORT=7777
      - RCON_PORT=27020
      - EXTRA_FLAGS=-NoBattlEye
      - EXTRA_SETTINGS=?serverPVE=1?AllowHitMarkers=True?DisableWeatherFog=true?DisableCryopodFridgeRequirement=true?NightTimeSpeedScale=2.0?DayTimeSpeedScale=0.5?OverrideStructurePlatformPrevention=True?AllowAnyoneBabyImprintCuddle=True?OverrideOfficialDifficulty=5.000000?EnablePVPGamma=True?OxygenSwimSpeedStatMultiplier=2.000000?DinoCharacterFoodDrainMultiplier=1.5?TamingSpeedMultiplier=10?DinoDamageMultiplier=2?DinoResistanceMultiplier=0.8?PlayerDamageMultiplier=2.0?StructureDamageMultiplier=2.0?StructureResistanceMultiplier=0.7?HarvestAmountMultiplier=5.0?HarvestHealthMultiplier=5.0?ResourcesRespawnPeriodMultiplier=50.0?PlayerCharacterFoodDrainMultiplier=0.25?PlayerCharacterHealthRecoveryMultiplier=2.00000?PlayerCharacterStaminaDrainMultiplier=0.7000?PlayerCharacterWaterDrainMultiplier=0.25?UseCorpseLocator=true?PerPlatformMaxStructuresMultiplier=5.00000?AllowFlyerCarryPvE=1?DisableStructureDecayPvE=1?DinoCharacterHealthRecoveryMultiplier=2?DinoCharacterStaminaDrainMultiplier=.70000?XPMultiplier=20.0?MaxPlatformSaddleStructureLimit=250?AllowFlyingStaminaRecovery=1?AllowMultipleAttachedC4=1
    env_file:
      - .env
    volumes:
      - ark-steam:/home/steam/Steam
      - ark-install:/home/steam/ark
      - ark-persistent-data:/home/steam/ark/ShooterGame/Saved

volumes:
  ark-persistent-data:
  ark-install:
  ark-steam:
