services:
  calibre:
    image: lscr.io/linuxserver/calibre:version-v9.13.0@sha256:f4a17653e7851c4642583ba2cd292509f90b4b8e123596af38b6ee02154676be
    container_name: calibre
    security_opt:
      - seccomp:unconfined # Required for GUI apps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS= # Optional Calibre CLI arguments
    volumes:
      - ./config:/config
      - ./custom-services.d:/custom-services.d:ro
      - ../../Media/books:/books
    ports:
      - 8090:8080   # Calibre desktop GUI (HTTP)
      - 8091:8181   # Calibre desktop GUI (HTTPS)
      - 8092:8081   # Calibre Content Server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1536M
    networks:
      - proxynet
    labels:
      - homepage.group=Media Consumption
      - homepage.name=Calibre
      - homepage.icon=calibre.png
      - homepage.href=https://calibre.benlawson.dev/
      - homepage.description=Ebook library management
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Consumption
      - swag.uptime-kuma.monitor.accepted_statuscodes=200-299,401

networks:
  proxynet:
    external: true
    name: proxynet
