services:
  # Bookshelf is an ebook and audiobook collection manager (Readarr fork)
  # https://github.com/pennydreadful/bookshelf
  bookshelf-audio:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf-audio
    volumes:
      - ../../Media/audiobooks:/audiobooks
      - ../../Media/downloads:/downloads
      - ./config:/config
    ports:
      - 8788:8787
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - homepage.group=Management
      - homepage.name=Bookshelf-Audio
      - homepage.icon=readarr.png
      - homepage.href=https://bookshelf-audio.benlawson.dev/
      - homepage.siteMonitor=http://bookshelf-audio:8787/ping
      - homepage.description=Audiobook management
      - homepage.widget.type=readarr
      - homepage.widget.url=http://bookshelf-audio:8787
      - homepage.widget.key=${BOOKSHELF_API_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
