services:
  cloudflared:
    image: cloudflare/cloudflared:2026.7.2
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Cloudflare Tunnel
      - homepage.icon=cloudflare-zero-trust.png
      - homepage.description=Secure tunnel to Cloudflare
      - homepage.widget.type=cloudflared
      - homepage.widget.accountid=${CLOUDFLARE_ACCOUNT_ID}
      - homepage.widget.tunnelid=${CLOUDFLARE_TUNNEL_ID}
      - homepage.widget.key=${CLOUDFLARE_API_TOKEN}
    networks:
      - proxynet

networks:
  proxynet:
    external: true
