services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-windows
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxynet

networks:
  proxynet:
    external: true
