version: "3"
services: 
  valheim: 
    image: lloesche/valheim-server
    container_name: valheim
    cap_add:
      - sys_nice
    volumes: 
      - E:\Docker\valheim\config:/config
      - E:\Docker\valheim\data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - E:\Docker\valheim\valheim.env
    restart: unless-stopped
    stop_grace_period: 2m
    labels:
      - homepage.group=Gaming
      - homepage.name=Valheim
      - homepage.icon=valheim.png
      - homepage.description=Valheim Server
      - homepage.showStats=true
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet