services:
  seerr:
    image: ghcr.io/rubiss/seerr:book-support
    container_name: seerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=debug
    volumes:
      - ./config:/app/config
    ports:
      - 5056:5055
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - proxynet
    labels:
      - homepage.group=Media Management
      - homepage.name=Seerr
      - homepage.icon=jellyseerr.png
      - homepage.href=https://request.benlawson.dev/
      - homepage.siteMonitor=http://seerr:5055
      - homepage.description=Media requests
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://seerr:5055
      - homepage.widget.key=${SEERR_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Management
      - swag.uptime-kuma.monitor.url=https://request.benlawson.dev

networks:
  proxynet:
    external: true
    name: proxynet
