services:
  # Bazarr is used to download and categorize subtitles
  # https://www.bazarr.media/
  bazarr:
    image: lscr.io/linuxserver/bazarr:version-v1.6.0@sha256:5d916d07404296ec35ee726e13e0e558f05952724cf494a7f009d913fb2b12f3
    container_name: bazarr
    volumes:
      - ../../Media/tv:/data/tv
      - ../../Media/movies:/data/movies
      - ./config:/config
    ports:
      - 6767:6767
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - path: .env
      - path: .env.secret
        required: false
    labels:
      - homepage.group=Media Management
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=https://bazarr.benlawson.dev/
      - homepage.siteMonitor=http://bazarr:6767/series
      - homepage.description=Captions management
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_API_KEY}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Media Management
      - swag.uptime-kuma.monitor.url=https://bazarr.benlawson.dev/series
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
