services:
  # Bazarr is used to download and categorize subtitles
  # https://www.bazarr.media/
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    volumes:
      - E:\Media\movies:/movies
      - E:\Media\tv:/tv
      - E:\Docker\bazarr\config:/config
    ports:
      - 6767:6767
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - homepage.group=Management
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=https://bazarr.benlawson.dev/
      - homepage.siteMonitor=http://bazarr:6767/series
      - homepage.description=Captions management
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_API_KEY}
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet
