services:
  minecraft-server:
    image: itzg/minecraft-server:java25@sha256:e77d5de73b2906f7f8d96b5fb920e840fc925fffad2fccd95ee637b7daee5a5b
    container_name: minecraft
    volumes:
      - ./data:/data
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      - TYPE=PAPER
      - VERSION=1.21.10
      - EULA=TRUE
      - OPS=Rubiss_
      - ENABLE_WHITELIST=true
      - MEMORY=10G
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      - homepage.group=Gaming
      - homepage.name=Minecraft
      - homepage.icon=minecraft.png
      - homepage.description=Minecraft Server
      - homepage.widget.type=minecraft
      - homepage.widget.url=udp://minecraft.benlawson.dev:25565
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet