services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.3@sha256:3e24e96c89efff0e3a4b0698cbdd36c15ad3022371db57166e5588853002ee5c
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - homepage.group=Observability
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=https://uptime.benlawson.dev/
      - homepage.siteMonitor=http://uptime-kuma:3001
      - homepage.description=Uptime metrics
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=http://uptime-kuma:3001
      - homepage.widget.slug=media-server
    networks:
      - proxynet
      - socket-proxy-net

networks:
  proxynet:
    name: proxynet
  socket-proxy-net:
    external: true
    name: socket-proxy-net
