services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.0@sha256:a8610b3b4c38077922ba51b036691e06887d7cefd91fe620fd3d6d23d03dc240
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - homepage.group=Observability
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=https://uptime.benlawson.dev/
      - homepage.siteMonitor=http://uptime-kuma:3001
      - homepage.description=Uptime metrics
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=http://uptime-kuma:3001
      - homepage.widget.slug=media-server
    networks:
      - proxynet
      - socket-proxy-net

networks:
  proxynet:
    name: proxynet
  socket-proxy-net:
    external: true
    name: socket-proxy-net
