services:
  homebridge:
    image: homebridge/homebridge:2026-08-05
    container_name: homebridge
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    network_mode: host
    environment:
      - TZ=America/New_York  # Change to your timezone
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Homebridge (Pi)
      - homepage.icon=homebridge.png
      - homepage.href=https://homebridge.benlawson.dev
      - homepage.description=HomeKit integration on Pi
      - homepage.siteMonitor=http://192.168.50.216:8581
      - homepage.widget.type=homebridge
      - homepage.widget.url=http://192.168.50.216:8581
      - homepage.widget.username=rubiss
      - homepage.widget.password=${HOMEBRIDGE_PASSWORD}
