---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

my-docker:
  host: dockerproxy
  port: 2375

pi-docker:
  host: 192.168.50.216
  port: 2375
