# https://gethomepage.dev/en/configs/services

- System:
    - NVIDIA GPU:
        icon: nvidia.svg
        description: GPU stats
        widget:
          type: customapi
          url: http://nvidia-smi-rest:7777
          refreshInterval: 5000
          mappings:
            - field:
                nvidia_smi_log:
                  gpu:
                    utilization: gpu_util
              label: GPU
              format: percent
            - field:
                nvidia_smi_log:
                  gpu:
                    fb_memory_usage: used
              label: VRAM
            - field:
                nvidia_smi_log:
                  gpu:
                    temperature: gpu_temp
              label: Temp
              suffix: "°C"
            - field:
                nvidia_smi_log:
                  gpu:
                    gpu_power_readings: power_draw
              label: Power

- Raspberry Pi:
    - Homebridge (Pi):
        icon: homebridge.png
        href: https://homebridge.benlawson.dev
        description: HomeKit integration on Pi
        siteMonitor: http://192.168.50.216:8581
        widget:
          type: homebridge
          url: http://192.168.50.40:8581
          username: admin
          password: {{HOMEPAGE_VAR_HOMEBRIDGE_PI_PASSWORD}}
    
    - Watchtower (Pi):
        icon: watchtower.png
        href: http://192.168.50.216:8081/v1/metrics
        description: Service updater on Pi
        siteMonitor: http://192.168.50.216:8081/v1/metrics
        widget:
          type: watchtower
          url: http://192.168.50.40:8080
          key: {{HOMEPAGE_VAR_WATCHTOWER_PI_KEY}}
    
    - Pi-hole:
        icon: pi-hole.png
        href: https://dns.benlawson.dev/admin
        description: Network-wide DNS ad blocking
        siteMonitor: http://192.168.50.216:80
        widget:
          type: pihole
          url: http://192.168.50.40:80
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
          version: 6
    
    - Pi System Monitor:
        icon: glances.png
        href: http://192.168.50.216:61208
        description: Pi 3 system stats
        siteMonitor: http://192.168.50.216:61208
        widget:
          type: glances
          url: http://192.168.50.216:61208
          version: 4
          metric: info
    
    - Speedtest (Pi):
        icon: speedtest-tracker.png
        href: https://speed-pi.benlawson.dev
        description: Pi internet speed tests
        siteMonitor: http://192.168.50.216:8082
        widget:
          type: speedtest
          url: http://192.168.50.216:8082

    - Cloudflare Tunnel (Pi):
        icon: cloudflare-zero-trust.png
        description: Secure tunnel to Cloudflare
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARE_PI_ACCOUNT_ID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_PI_TUNNEL_ID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARE_PI_KEY}}

- Media:
    - HDHomeRun:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 0
          fields: ["clientIP", "channels", "hd", "tunerCount"]
    - HDHomeRun Tuner 0:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 0
          fields: ["channelNumber", "channelNetwork", "signalStrength", "signalQuality"]
    - HDHomeRun Tuner 1:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 1
          fields: ["channelNumber", "channelNetwork", "signalStrength", "signalQuality"]
