# https://gethomepage.dev/en/configs/services

- Hardware:
    - NVIDIA GPU:
        icon: nvidia.svg
        description: GPU stats
        widget:
          type: customapi
          url: http://nvidia-smi-rest:7777
          refreshInterval: 5000
          mappings:
            - field:
                nvidia_smi_log:
                  gpu:
                    utilization: gpu_util
              label: GPU
              format: percent
            - field:
                nvidia_smi_log:
                  gpu:
                    fb_memory_usage: used
              label: VRAM
            - field:
                nvidia_smi_log:
                  gpu:
                    temperature: gpu_temp
              label: Temp
              suffix: "°C"
            - field:
                nvidia_smi_log:
                  gpu:
                    gpu_power_readings: power_draw
              label: Power
    - HDHomeRun:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 0
          fields: ["clientIP", "channels", "hd", "tunerCount"]
    - HDHomeRun Tuner 0:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 0
          fields: ["channelNumber", "channelNetwork", "signalStrength", "signalQuality"]
    - HDHomeRun Tuner 1:
        icon: hdhomerun.png
        href: http://192.168.50.130
        siteMonitor: http://192.168.50.130
        description: Over The Air TV
        widget:
          type: hdhomerun
          url: http://192.168.50.130
          tuner: 1
          fields: ["channelNumber", "channelNetwork", "signalStrength", "signalQuality"]
