---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

base: https://homepage.benlawson.dev/
headerStyle: clean
maxGroupColumns: 8 # default is 4 for services, 6 for bookmarks, max 8
layout:
  - Downloads:
      header: false
      style: row
  - Infrastructure:
  - Observability:
  - Media Management:
  - Other:
      header: false
      Media Consumption:
      AI & Automation:
  - Gaming:
