---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

base: https://homepage.benlawson.dev/
headerStyle: clean
fullWidth: true
maxGroupColumns: 5
layout:
  - Downloads:
      header: false
      style: row
      columns: 3
  - Infrastructure:
  - Observability:
  - Media Management:
  - Media Consumption:
  - AI & Automation:
  - Hardware:
  - Gaming:
  - Developer:
      header: false
