services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - homepage.group=Observability
      - homepage.name=Influxdb
      - homepage.icon=influxdb.png
      - homepage.href=https://influx.benlawson.dev/
      - homepage.siteMonitor=http://influxdb:8086/health
      - homepage.description=Metrics database
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=Observability
      - swag.uptime-kuma.monitor.url=https://influx.benlawson.dev/health
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: proxynet
