#!/usr/bin/with-contenv bash

set -e

exec s6-setuidgid abc calibre-server \
  --listen-on 0.0.0.0 \
  --port 8081 \
  --enable-auth \
  --userdb /config/.config/calibre/server-users.sqlite \
  --log /config/calibre-server.log \
  --access-log /config/calibre-server-access.log \
  /books