services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:2026.6.11@sha256:3814fb1f62f9cfc5944de088c5817c68c88b5d721feebe36420b666a90a61ce7
    container_name: openclaw-gateway
    user: root
    environment:
      HOME: /home/node
      TERM: xterm-256color
      DOCKER_HOST: tcp://socket-proxy:2375
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - ./config:/home/node/.openclaw
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--allow-unconfigured",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "${OPENCLAW_GATEWAY_PORT:-18789}",
      ]
    networks:
      - ollama-net
      - proxynet
      - socket-proxy-net
    labels:
      - homepage.group=AI & Automation
      - homepage.name=OpenClaw
      - homepage.icon=/icons/openclaw.png
      - homepage.href=https://openclaw.benlawson.dev/?token=${OPENCLAW_GATEWAY_TOKEN}
      - homepage.description=AI Gateway Service
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.parent=AI & Automation
      - swag.uptime-kuma.monitor.url=https://openclaw.benlawson.dev/

  openclaw-cli:
    image: ghcr.io/openclaw/openclaw:2026.6.11@sha256:3814fb1f62f9cfc5944de088c5817c68c88b5d721feebe36420b666a90a61ce7
    container_name: openclaw-cli
    user: root
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - ./config:/home/node/.openclaw
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
    networks:
      - ollama-net
      - proxynet

networks:
  ollama-net:
    external: true
    name: ollama-net
  proxynet:
    external: true
    name: proxynet
  socket-proxy-net:
    external: true
    name: socket-proxy-net
