## Custom config for classroom-librarian
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name classroom-librarian.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app classroom-librarian;
        set $upstream_port 4000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
