## Version 2025/11/29
# Glances proxy configuration for Raspberry Pi
# Proxies to external Pi IP since it's not on the same Docker network

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name glances.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.50.216;
        set $upstream_port 61208;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
